# app/config/routing.yml
login:
    path:     /login
    defaults: { _controller: NHKSecurityBundle:Security:login }
    
login_check:
    path: /login_check
    
logout:
    path:     /logout
    
nhk_qc:
    resource: "@NHKQcBundle/Resources/config/routing.yml"
    prefix:   /
    
nhk_security:
    resource: "@NHKSecurityBundle/Resources/config/routing.yml"
    prefix:   /    

