nhk_qc_homepage:
    path:     /
    defaults: { _controller: NHKQcBundle:Default:index }
    
nhk_qc_user:
    resource: "@NHKQcBundle/Resources/config/routes/user_routing.yml"
    prefix:   /user

nhk_qc_setup_data:
    resource: "@NHKQcBundle/Resources/config/routes/setup_data_routing.yml"
    prefix:   /set-up-data

nhk_qc_machine:
    resource: "@NHKQcBundle/Resources/config/routes/machine_routing.yml"
    prefix:   /machine
